### ISSUE TITLE
Firmware upgrades on MX

### ISSUE THREAD

**Issue by thomasnoppe** [CiscoDevNet/terraform-provider-meraki#28]
Hi,

The option to enable beta firmware and schedule the maintenance window for a Meraki network is not available.

kind regards

**Comment by danischm** [comment]
Added here: https://github.com/CiscoDevNet/terraform-provider-meraki/commit/62d1bb3a2e5bd58c8b73075794d8a334a23459c7

**Comment by danischm** [comment]
Added in v0.1.3 release.
